version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./assets:/app/assets
      - ./certificates:/app/certificates
    environment:
      - DEBUG=False
      - PORT=7860
      - SHARE=False
      - FORCE_CPU=False
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

